### ISSUE TITLE
"connection" never fires on iojs

### ISSUE THREAD

**Issue by silverwind** [einaros/ws#439] opened 2015-01-18 16:03 UTC
Seeing this by simply switching the binary from node 0.10.35 to iojs 1.0.2 on both `ws://` and `wss://` protocols, not sure what's happening. The node 0.11.x branch might be affected too.

**Comment by silverwind** [comment] 2015-01-18 16:09
Just saw https://github.com/einaros/ws/commit/571886d6444a6f1c95a8a48d807fff50b444e8fb, will test with HEAD.

**Comment by silverwind** [comment] 2015-01-18 16:13
HEAD still affected it seems.

**Comment by silverwind** [comment] 2015-01-22 22:14
Update: It seems it's working on Linux iojs 1.0.3, I'll retest on Windows which was showing this issue.

**Comment by 3rd-Eden** [comment] 2015-01-23 07:56
@silverwind I cannot reproduce this on iojs. All tests seem to pass on 1.0.3 so i'm going to close this issue.

**Closed by 3rd-Eden** 2015-01-23 07:56 UTC

**Comment by silverwind** [comment] 2015-01-23 18:43
Well, I can only tell you that the HTTP Upgrade request isn't being responded to at all, pointing to either this library or iojs/node 0.11.x. Here's the packet from the client:

````
`Frame 98: 559 bytes on wire (4472 bits), 559 bytes captured (4472 bits)
Raw packet data
Internet Protocol Version 4, Src: 127.0.0.1 (127.0.0.1), Dst: 127.0.0.1 (127.0.0.1)
Transmission Control Protocol, Src Port: 3258 (3258), Dst Port: 8989 (8989), Seq: 1, Ack: 1, Len: 519
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
    Host: localhost:8989\r\n
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0\r\n
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n
    Accept-Language: en-US,en;q=0.5\r\n
    Accept-Encoding: gzip, deflate\r\n
    Sec-WebSocket-Version: 13\r\n
    Origin: http://localhost:8989\r\n
    Sec-WebSocket-Key: LCDSLtOtfufP3W706y+1bw==\r\n
    Cookie: s=tJTkrO8mlzGBz/K3HUzcf3TnS5pJbfAJJ8FtzPznnCA=\r\n
    Connection: keep-alive, Upgrade\r\n
    Pragma: no-cache\r\n
    Cache-Control: no-cache\r\n
    Upgrade: websocket\r\n
    \r\n
    [Full request URI: http://localhost:8989/]
    [HTTP request 1/1]
````

You should be able to reproduce with Firefox and any version of io.js.

**Comment by silverwind** [comment] 2015-01-24 14:08
FYI: https://github.com/iojs/io.js/issues/588
